#!/bin/bash
# For correct solarized handling in terminal
export TERM=xterm-direct

# For ssh-agent support
export SSH_AUTH_SOCK=$(fish -c 'echo $SSH_AUTH_SOCK')

exec emacsclient --alternate-editor="" -c "$@"
