#!/bin/bash

if [[ "$INSIDE_EMACS" = 'vterm' || "$INSIDE_EMACS" = 'ghostel' ]]; then
    # already inside emacs, no funny business
    exec emacsclient "$@"
fi

exec emacsclient --alternate-editor="" -c "$@"
