#! /usr/bin/env bash
# default init NOTMUCH_PATH
NOTMUCH_PATH=${NOTMUCH_PATH:-""}

if [[ "" = $NOTMUCH_PATH ]] ; then
    # Find the notmuch to run
    IFS=':' read -ra PATH_ARRAY <<< "$PATH"
    for SEARCH_PATH in "${PATH_ARRAY[@]}" ; do
	NOTMUCH_PATH=$(find $SEARCH_PATH -executable -regex '.+/notmuch$' 2> /dev/null | grep --invert-match $0 | head -n1)
	if [[ $NOTMUCH_PATH != "" ]] ; then
	    break
	fi
    done
    if [[ $NOTMUCH_PATH = "" ]] ; then
	echo "Could not find notmuch!" 1>&2
	exit 255
    fi
fi

# print which notmuch binary I am launching
echo "Launching notmuch binary at" $NOTMUCH_PATH

exec env LD_LIBRARY_PATH=/usr0/home/rraghuna/.toast/pkg/zlib/v1.2.8/1/root/lib:$LD_LIBRARY_PATH "$NOTMUCH_PATH" "$@"
